version: '3.8'

services:
  angular-app:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - spring-boot-app
    container_name: todo-frontend
    restart: unless-stopped

  spring-boot-app:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    container_name: todo-backend
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    restart: unless-stopped

  postgres_db:
    image: postgres:17
    container_name: postgres-container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
